services:
  mongo-inventory:
    image: mongo:7
    container_name: mongo-inventory
    ports:
      - "27018:27017"
    volumes:
      - mongo_inventory_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand({ ping: 1 }).ok\" | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATA_MONGODB_URI: mongodb://mongo-inventory:27017/inventorydb
    depends_on:
      mongo-inventory:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo_inventory_data: