debug: true
logging:
  level:
    org.springframework.boot.actuate: DEBUG

spring:
  application:
    name: inventory-service

  data:
    mongodb:
      auto-index-creation: true

server:
  port: 8082

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always